import { Pet } from '@/types';

export const mockPets: Pet[] = [
  {
    id: 'mock-pet-1',
    name: 'Max',
    species: 'Dog',
    breed: 'Golden Retriever Mix',
    age: 3,
    size: 'Large',
    sex: 'male',
    weight: 65,
    temperament: ['Friendly', 'Playful', 'Energetic'],
    description: 'Max is a loving and energetic golden retriever mix who adores playing fetch and long walks. He is great with kids and other dogs, making him perfect for an active family.',
    imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2253275/pexels-photo-2253275.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-1',
    availableForAdoption: true,
    traits: {
      energyLevel: 'High',
      kidFriendly: true,
      dogFriendly: true,
      catFriendly: true,
    },
    behavior: {
      notes: 'Well-trained and obedient. Knows basic commands.',
      training: 'House-trained, leash-trained',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Up to date on all vaccinations',
    },
  },
  {
    id: 'mock-pet-2',
    name: 'Luna',
    species: 'Cat',
    breed: 'Domestic Shorthair',
    age: 2,
    size: 'Medium',
    sex: 'female',
    weight: 10,
    temperament: ['Calm', 'Affectionate', 'Independent'],
    description: 'Luna is a sweet and gentle cat who loves cuddles and sunny windowsills. She would thrive in a quiet home where she can be the center of attention.',
    imageUrl: 'https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-1',
    availableForAdoption: true,
    traits: {
      energyLevel: 'Low',
      kidFriendly: true,
      dogFriendly: false,
      catFriendly: false,
    },
    behavior: {
      notes: 'Prefers to be the only pet. Loves quiet environments.',
      training: 'Litter-trained',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Healthy and up to date',
    },
  },
  {
    id: 'mock-pet-3',
    name: 'Charlie',
    species: 'Dog',
    breed: 'Labrador Retriever Mix',
    age: 4,
    size: 'Large',
    sex: 'male',
    weight: 70,
    temperament: ['Loyal', 'Gentle', 'Friendly'],
    description: 'Charlie is a gentle giant with a heart of gold. He loves everyone he meets and is wonderful with children of all ages.',
    imageUrl: 'https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-2',
    availableForAdoption: true,
    traits: {
      energyLevel: 'Medium',
      kidFriendly: true,
      dogFriendly: true,
      catFriendly: true,
    },
    behavior: {
      notes: 'Very calm and well-mannered. Great for families.',
      training: 'Fully trained, knows many commands',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Clean bill of health',
    },
  },
  {
    id: 'mock-pet-4',
    name: 'Bella',
    species: 'Dog',
    breed: 'Beagle Mix',
    age: 2,
    size: 'Medium',
    sex: 'female',
    weight: 35,
    temperament: ['Playful', 'Curious', 'Energetic'],
    description: 'Bella is a curious and playful beagle mix who loves exploring and sniffing everything. She would do best with an active owner who enjoys outdoor adventures.',
    imageUrl: 'https://images.pexels.com/photos/1490908/pexels-photo-1490908.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1490908/pexels-photo-1490908.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/825947/pexels-photo-825947.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-2',
    availableForAdoption: true,
    traits: {
      energyLevel: 'High',
      kidFriendly: true,
      dogFriendly: true,
      catFriendly: false,
    },
    behavior: {
      notes: 'Needs regular exercise and mental stimulation.',
      training: 'House-trained, learning commands',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Healthy and active',
    },
  },
  {
    id: 'mock-pet-5',
    name: 'Whiskers',
    species: 'Cat',
    breed: 'Tabby Mix',
    age: 5,
    size: 'Medium',
    sex: 'male',
    weight: 12,
    temperament: ['Laid-back', 'Affectionate', 'Social'],
    description: 'Whiskers is a laid-back tabby who loves lounging around and getting head scratches. He gets along great with other cats and dogs.',
    imageUrl: 'https://images.pexels.com/photos/1543793/pexels-photo-1543793.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1543793/pexels-photo-1543793.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1710482/pexels-photo-1710482.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-1',
    availableForAdoption: true,
    traits: {
      energyLevel: 'Low',
      kidFriendly: true,
      dogFriendly: true,
      catFriendly: true,
    },
    behavior: {
      notes: 'Very social and adaptable to new environments.',
      training: 'Litter-trained',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Senior wellness check completed',
    },
  },
  {
    id: 'mock-pet-6',
    name: 'Rocky',
    species: 'Dog',
    breed: 'German Shepherd Mix',
    age: 5,
    size: 'Large',
    sex: 'male',
    weight: 75,
    temperament: ['Protective', 'Loyal', 'Intelligent'],
    description: 'Rocky is a smart and loyal German Shepherd mix who would make an excellent companion for someone looking for a protective and devoted friend.',
    imageUrl: 'https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/333083/pexels-photo-333083.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1390361/pexels-photo-1390361.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-2',
    availableForAdoption: true,
    traits: {
      energyLevel: 'Medium',
      kidFriendly: true,
      dogFriendly: false,
      catFriendly: false,
    },
    behavior: {
      notes: 'Best as an only pet. Needs experienced owner.',
      training: 'Well-trained, responds to commands',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Healthy, regular vet visits',
    },
  },
  {
    id: 'mock-pet-7',
    name: 'Daisy',
    species: 'Dog',
    breed: 'Border Collie Mix',
    age: 3,
    size: 'Medium',
    sex: 'female',
    weight: 45,
    temperament: ['Smart', 'Energetic', 'Playful'],
    description: 'Daisy is an incredibly smart and energetic border collie mix who loves learning new tricks and playing games. Perfect for an active family!',
    imageUrl: 'https://images.pexels.com/photos/1458916/pexels-photo-1458916.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1458916/pexels-photo-1458916.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/162149/dog-border-collie-light-blue-eyes-162149.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-1',
    availableForAdoption: true,
    traits: {
      energyLevel: 'High',
      kidFriendly: true,
      dogFriendly: true,
      catFriendly: true,
    },
    behavior: {
      notes: 'Needs lots of mental and physical stimulation.',
      training: 'Highly trainable, knows many tricks',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Perfect health',
    },
  },
  {
    id: 'mock-pet-8',
    name: 'Oliver',
    species: 'Cat',
    breed: 'Tuxedo',
    age: 1,
    size: 'Small',
    sex: 'male',
    weight: 8,
    temperament: ['Playful', 'Curious', 'Energetic'],
    description: 'Oliver is a young and playful tuxedo cat full of energy and curiosity. He loves interactive toys and would thrive with an engaged owner.',
    imageUrl: 'https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1543793/pexels-photo-1543793.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-2',
    availableForAdoption: true,
    traits: {
      energyLevel: 'High',
      kidFriendly: true,
      dogFriendly: false,
      catFriendly: true,
    },
    behavior: {
      notes: 'Very playful kitten. Needs lots of toys.',
      training: 'Litter-trained',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Young and healthy',
    },
  },
  {
    id: 'mock-pet-9',
    name: 'Cooper',
    species: 'Dog',
    breed: 'Pit Bull Mix',
    age: 4,
    size: 'Large',
    sex: 'male',
    weight: 60,
    temperament: ['Affectionate', 'Loyal', 'Gentle'],
    description: 'Cooper is a sweet and affectionate pit bull mix who just wants to be loved. Despite his tough exterior, he is a gentle soul who adores cuddles.',
    imageUrl: 'https://images.pexels.com/photos/1629781/pexels-photo-1629781.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1629781/pexels-photo-1629781.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1322182/pexels-photo-1322182.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-1',
    availableForAdoption: true,
    traits: {
      energyLevel: 'Medium',
      kidFriendly: true,
      dogFriendly: true,
      catFriendly: false,
    },
    behavior: {
      notes: 'Very affectionate and people-oriented.',
      training: 'House-trained and leash-trained',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Healthy and strong',
    },
  },
  {
    id: 'mock-pet-10',
    name: 'Mittens',
    species: 'Cat',
    breed: 'Calico',
    age: 3,
    size: 'Small',
    sex: 'female',
    weight: 9,
    temperament: ['Sweet', 'Gentle', 'Calm'],
    description: 'Mittens is a beautiful calico with a sweet and gentle personality. She loves quiet environments and would be perfect for a calm household.',
    imageUrl: 'https://images.pexels.com/photos/1056251/pexels-photo-1056251.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1056251/pexels-photo-1056251.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1472999/pexels-photo-1472999.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    shelterId: 'shelter-2',
    availableForAdoption: true,
    traits: {
      energyLevel: 'Low',
      kidFriendly: true,
      dogFriendly: false,
      catFriendly: true,
    },
    behavior: {
      notes: 'Prefers calm and quiet environments.',
      training: 'Litter-trained',
    },
    health: {
      vaccinated: true,
      spayedNeutered: true,
      specialNeeds: '',
      medicalHistory: 'Healthy',
    },
  },
];
